### ISSUE TITLE
LmP v88 - NICMx/Jool.git: Unable to find revision 4c3e99d00242cf54832985fbe5374225512de3d5

### ISSUE THREAD

**Issue by Dono-Harjanto** [foundriesio/lmp-manifest#271]
Getting the following error while building lmp-gateway-image:

`ERROR: Fetcher failure: Unable to find revision 4c3e99d00242cf54832985fbe5374225512de3d5 in branch master even from upstream
ERROR: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://github.com/NICMx/Jool.git;protocol=https;branch=master')`

**Comment by ricardosalveti** [comment]
This is because the upstream repository renamed the branch from master to main.

Apply locally the following patch:

```
diff --git a/meta-lmp-base/recipes-kernel/jool/jool_git.bb b/meta-lmp-base/recipes-kernel/jool/jool_git.bb
index 6fb45102..221d74e6 100644
--- a/meta-lmp-base/recipes-kernel/jool/jool_git.bb
+++ b/meta-lmp-base/recipes-kernel/jool/jool_git.bb
@@ -5,7 +5,7 @@ SECTION = "kernel/network"
 LICENSE = "GPL-2.0-only"
 LIC_FILES_CHKSUM = "file://${S}/COPYING;md5=b234ee4d69f5fce4486a80fdaf4a4263"

-SRC_URI = "git://github.com/NICMx/Jool.git;protocol=https;branch=master"
+SRC_URI = "git://github.com/NICMx/Jool.git;protocol=https;branch=main"

 PV = "4.0.4"
 SRCREV = "4c3e99d00242cf54832985fbe5374225512de3d5"
```

Will propose the fix to get this updated for v89.

Or use lmp-base-console-image instead of gateway, where jool is not included by default (unless required by you).

**Comment by Dono-Harjanto** [comment]
The patch solved the issue. Thank you @ricardosalveti
